### PR TITLE
Rename local-certs to local-config

### PR DESCRIPTION
**Pull request by dixonwhitmire**
This PR takes a first step at simplifying pki/certs and configuration for local and deployed environments by renaming the project's local-certs directory to local-config. I'm opting for local-config since the directory contains tools/things used to configure pki (certificate stuff) in addition to NATS configuration (conf file and nkey). The changes in this PR are minimal to support the directory rename.

Once this PR is accepted, the next step is to cleanup the resources in the connect container. I think that we can do this by updating our Dockerfile to support volume mounts which are "pre-populated" for the local environment use-case.

Changes include:
- updated local-config README
- dockerignore
- gitignore
- Dockerfile
- Docker Compose config
- K8s documentation
- certificate install/remove scripts.

### CODE REVIEW

**Comment by ccorley** [comment]
I think we still need to move nats-server.conf and nats-server.nk to their new homes.  All I see in this PR is that they've been deleted.

**Review by ccorley — CHANGES_REQUESTED** [review]
It looks like nats-server.conf and nats-server.nk need to be added to local-config/nats?

**Comment by dixonwhitmire** [comment]
> It looks like nats-server.conf and nats-server.nk need to be added to local-config/nats?

Hey @ccorley ! Good catch. I added the files back in with this [commit](https://github.com/LinuxForHealth/connect/pull/156/commits/a1933fb917b3445659645d7adf1c27f415dcf762)

**Review by ccorley — APPROVED** [review]
Nice work on a pervasive change!

**Pull request merged**
