### PR TITLE
Eligibility Demo Updates

### PR DESCRIPTION
**Pull request by dixonwhitmire**
This PR applies selective code/features from the `eligibility-demo` branch to  the `master` branch.

* LinuxForHealth Metadata Record support for multiple target servers and attributes (headers)
* Core workflow updates to support multiple target server persistence and transmission
* MSFT FHIR Support for the compose fhir profile

### CODE REVIEW

**Review by ccorley — CHANGES_REQUESTED** [review]
This looks good, thanks for doing this.  I think the nats.py change is missing, so we need to add that before merging.

**Comment by dixonwhitmire** [comment]
Thanks @ccorley - the `handle_fhir_resources`  function is used in nats.py by  the nats_coverage_eligibility_event_handler

https://github.com/LinuxForHealth/connect/blob/eligibility-demo/connect/clients/nats.py#L196

Do we want to include this function in the main branch?

**Comment by ccorley** [comment]
You're right @dixonwhitmire - and it's good that the coverage eligibility subscriber isn't included in this PR, so we can go ahead and merge.

**Review by ccorley — APPROVED** [review]

**Comment by dixonwhitmire** [comment]
@ccorley - thanks for the review. I have resolved the merge conflicts and tested with the following configs/setups:

* Posting to a non-fhir server where `connect_generate_fhir_server_url` is False
* Postting to multiple fhir servers where `connect_generate_fhir_server_url` is True

**Pull request merged**
